"""Regenerate battlechain/abi.py from cyfrin/battlechain-lib forge artifacts.

The canonical source of each ABI is forge's compiled output:
    <battlechain-lib>/out/<Interface>.sol/<Interface>.json

This script takes a path to a `battlechain-lib` working copy, runs `forge build`
to ensure the artifacts are fresh, and emits `battlechain/abi.py`.

Usage:
    python tools/gen_abi.py                       # defaults to ../battlechain-lib
    python tools/gen_abi.py /path/to/battlechain-lib
    python tools/gen_abi.py --no-build /path/to/battlechain-lib  # skip forge build
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

# Maps the forge interface artifact to the Python constant name we emit.
ARTIFACTS = {
    "IAgreementFactory": "AGREEMENT_FACTORY_ABI",
    "IAgreement": "AGREEMENT_ABI",
    "IAttackRegistry": "ATTACK_REGISTRY_ABI",
    "IBCSafeHarborRegistry": "REGISTRY_ABI",
    "IBCDeployer": "DEPLOYER_ABI",
}

DEFAULT_LIB_PATH = Path(__file__).resolve().parent.parent.parent / "battlechain-lib"
TARGET = Path(__file__).resolve().parent.parent / "battlechain" / "abi.py"


def run_forge_build(lib_root: Path) -> None:
    """Run `forge build` inside the battlechain-lib working copy."""
    print(f"Running forge build in {lib_root}...")
    result = subprocess.run(
        ["forge", "build"],
        cwd=lib_root,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        sys.exit(
            f"forge build failed (exit {result.returncode}):\n"
            f"stdout:\n{result.stdout}\n"
            f"stderr:\n{result.stderr}"
        )


def load_abi(lib_root: Path, interface: str) -> list[dict]:
    """Read the `abi` field from out/<Interface>.sol/<Interface>.json."""
    artifact = lib_root / "out" / f"{interface}.sol" / f"{interface}.json"
    if not artifact.is_file():
        sys.exit(f"Missing artifact: {artifact}\nDid `forge build` succeed?")
    data = json.loads(artifact.read_text())
    if "abi" not in data:
        sys.exit(f"Artifact has no `abi` field: {artifact}")
    return data["abi"]


def render_module(abis: dict[str, list[dict]]) -> str:
    header = '''"""ABI fragments for BattleChain protocol contracts.

Auto-generated by tools/gen_abi.py from cyfrin/battlechain-lib forge artifacts.
Do not edit manually — regenerate with:
    python tools/gen_abi.py [/path/to/battlechain-lib]
"""

from typing import Any

# Each ABI is a list of function/event definitions in the standard JSON format
# accepted by boa.loads_abi(...) and web3.py.
'''
    chunks = [header]
    for interface, py_name in ARTIFACTS.items():
        rendered = json.dumps(abis[interface], indent=4)
        chunks.append(
            f"\n# Source: out/{interface}.sol/{interface}.json\n"
            f"{py_name}: list[dict[str, Any]] = {rendered}\n"
        )
    chunks.append(
        "\n\n__all__ = [\n"
        + "".join(f'    "{name}",\n' for name in ARTIFACTS.values())
        + "]\n"
    )
    return "".join(chunks)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "lib_path",
        nargs="?",
        type=Path,
        default=DEFAULT_LIB_PATH,
        help=f"Path to battlechain-lib (default: {DEFAULT_LIB_PATH})",
    )
    parser.add_argument(
        "--no-build",
        action="store_true",
        help="Skip `forge build` and use existing artifacts in out/",
    )
    args = parser.parse_args()

    lib_root = args.lib_path.expanduser().resolve()
    if not lib_root.is_dir():
        sys.exit(f"Not a directory: {lib_root}")
    if not (lib_root / "foundry.toml").is_file():
        sys.exit(f"Not a Foundry project (no foundry.toml): {lib_root}")

    if not args.no_build:
        run_forge_build(lib_root)

    abis = {iface: load_abi(lib_root, iface) for iface in ARTIFACTS}
    TARGET.write_text(render_module(abis))

    counts = ", ".join(f"{name}={len(abi)}" for name, abi in abis.items())
    print(f"Wrote {TARGET}")
    print(f"  {counts}")


if __name__ == "__main__":
    main()
